### ISSUE TITLE
TODO v1.0

### ISSUE THREAD

**Issue by robinvdvleuten** [webstronauts/draft-php#3]
- [ ] Make BlockMap a collection instance instead of an ordered map.

**Comment by aight8** [comment]
ContentState :: Add missing getKeyBefore(), getKeyAfter() and getBlockBefore(), getBlockAfter() methods.
-> #4

**Comment by aight8** [comment]
okey I fixed that part.

**Comment by aight8** [comment]
- [] Move entity map to content state - new draftjs specs. It's more isolated now.

**Comment by aight8** [comment]
To be really safe with handling draftjs data structures I made some notes about validation:

Starting point:
```
```
entityMap[]
- type:string
- mutability:enum((MUTABLE|IMMUTABLE|SEGMENTED))
- data:array

blocks[]
- key:string
- type:string
- text:string
- type:string
- depth:number
- inlineStyleRanges[]
	- offset:number
	- length:number
	- style:string
- entityRanges[]
	- offset:number
	- length:number
	- key:number
```

**Possible validations:**

##### Valid depth
- [] depth > 0 only when list type
- [] when list type: downstairs stepping. 0, 1, 2, 3, 4 until MAX_DEPTH

##### Valid key
- [] String length: 5, Alphanum

##### Valid type
- [] type: **VALID TYPES** - custom given as argument by use case?

##### Valid text
- [] no new line

##### Valid inlineStyleRanges
- [] offset >= 0, offset < TEXT_LENGTH - 1
- [] length >= 1, offset + length <= TEXT_LENGTH
- [] style: **VALID STYLES** - custom given as argument by use case?

##### Valid entityRanges
- [] offset >= 0, offset < TEXT_LENGTH - 1
- [] length >= 1, offset + length <= TEXT_LENGTH
- [] key: must exist in entity map (?)

##### Valid entity
- [ ] type: key: **VALID ENTITY TYPES** - custom given as argument by use case?
- [ ] mutability: one of: MUTABLE, IMMUTABLE, SEGMENTED
- [ ] data: hash - where is the limit?

**Comment by aight8** [comment]
@robinvdvleuten I wrote down my plans and research. Let's discuss a bit when you have time. I want to help to make a great library for draftjs state processing out of this  👍 

Do you use this library in some projects already?

**Comment by robinvdvleuten** [comment]
@aight8 thanks for the thorough research, big props for what you're doing here! I've used on a large project as a proof of concept to integrate draft.js with a Symfony application. But in the end we went to converting to markdown first before sending it to the backend. I still have plans to use it on some other projects I am currently working on and continue development on this library. I really believe the Draft.js' Entity structure is a very good approach for modelling a content management system in php compared to phpcr for example. And can definitely use some help here to make it an awesome library :smile: 

I've developed most of the functionality by mimicking the test cases from Draft.js (as you can probably see by looking at [this file](https://github.com/facebook/draft-js/blob/master/src/model/entity/__tests__/DraftEntity-test.js) and I would like to try to stay as close to these as possible. 

Maybe it's an idea that you split your notes to separate issues and that I move this 1.0 issue to a milestone to not have multiple topics in the same issue?

**Comment by aight8** [comment]
### Additional ideas to discuss:

There are some last things, before this library reaches it's stable version:

CharacterMetadata::style = DraftStyle object ? immutable OrderedList like object to avoid the workarounds (inline style order becomes not relevant)
Sadly there are no __compare magic function in PHP. So to make it work to compare to styles with PHP's === it must be the same object as well like in draft.js.

There is sadly no method to prevent to use **strlen($contentBlock->getText())** it must be documented very well that this will return not the last offset or the real text length by characters.

---

There are some points implemented in your TODO list. Some or not definitely (Global, BlockMap).
Any infos about those?
Are you planning to implement those?
